version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: MartO4055
      MYSQL_DATABASE: crud
      MYSQL_USER: leomarto
      MYSQL_PASSWORD: marto4055
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: MartO4055
    ports:
      - "8081:80"
    depends_on:
      - mysql
  python:
    image: leomarto/python:latest
    ports:
      - "5000:5000"
    environment:
      HOST_DB: mysql
      USER_DB: leomarto
      PASS_DB: marto4055
      DATABASE_DB: crud

volumes:
  mysql_data:
